spring:
  config:
    import: optional:aws-parameterstore:/rds/prod/

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}

  cloud:
    aws:
      region:
        static: ap-northeast-2

      s3:
        bucket: ${s3-bucket}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    team-name: ${team-name}